#!/bin/sh

# Xcode Cloud pre-build script
# Generates Secrets.xcconfig from environment variables set in App Store Connect

set -e

SECRETS_FILE="$CI_PRIMARY_REPOSITORY_PATH/Roost_iOS/Config/Secrets.xcconfig"

cat > "$SECRETS_FILE" << EOF
SUPABASE_HOST = ${SUPABASE_HOST}
SUPABASE_ANON_KEY = ${SUPABASE_ANON_KEY}
GOOGLE_CLIENT_ID = ${GOOGLE_CLIENT_ID}
STRIPE_ANNUAL_PRICE_ID = ${STRIPE_ANNUAL_PRICE_ID}
STRIPE_CHECKOUT_ENDPOINT = ${STRIPE_CHECKOUT_ENDPOINT}
STRIPE_MONTHLY_PRICE_ID = ${STRIPE_MONTHLY_PRICE_ID}
STRIPE_PORTAL_ENDPOINT = ${STRIPE_PORTAL_ENDPOINT}
STRIPE_PRICES_ENDPOINT = ${STRIPE_PRICES_ENDPOINT}
EOF

echo "Secrets.xcconfig generated successfully."
